New folder/faculty/urls.py
from django.urls import path
from . import views



app_name = "faculties"


urlpatterns = [
    path('create/new/faculty/', views.CreateFaculty, name='create_faculty'),

    path('UIC/<faculty_slug>/edit/', views.UpdateFaculty.as_view(), name='update_faculty'),

    path('UIC/all/', views.FacultyList.as_view(), name='faculty_list'),
    path('UIC/<faculty_slug>/departments/', views.FacultyDetail.as_view(), name='faculty_detail'),
    path('UIC/<faculty_slug>/delete', views.FacultyDelete.as_view(), name='delete_faculty'),

    path('UIC/form/upload/images', views.facutyimages, name='gallery_form'),
    path('UIC/gallery/', views.ImageList.as_view(), name='varsity_images'),

]

UniversityWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('about/', views.about),
#     path('', views.homepage, name='index'),
#     path('contact_us/', views.contact_us, name='contact_us'),
#     # path('students/', include('students.urls')),
#     path('faculties/', include("faculties.urls")),
#     path('departments/', include("departments.urls")),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.AllFacultyList.as_view() , name='index'),
    # path('contact_us/', views.contact_us, name='contact_us'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('faculties/', include("faculties.urls", namespace="faculties")),
    path('departments/', include("departments.urls", namespace='departments')),
    path('students/', include("students.urls", namespace='students')),
    path('teachers/', include("teachers.urls", namespace='teachers')),

    # re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

departments/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
#from django.conf.urls import url
app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('CUS/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('CUS/<faculty_slug>/edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('CUS/<faculty_slug>/<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('CUS/<faculty_slug>/department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

faculties/urls.py
from django.urls import path
from . import views



app_name = 'faculties'


urlpatterns = [
    path('create/new/faculty/', views.CreateFaculty, name='create_faculty'),

    path('CUS/<faculty_slug>/edit/', views.UpdateFaculty.as_view(), name='update_faculty'),

    path('CUS/all/', views.FacultyList.as_view(), name='faculty_list'),
    path('CUS/<faculty_slug>/departments/', views.FacultyDetail.as_view(), name='faculty_detail'),
    path('CUS/<faculty_slug>/delete', views.FacultyDelete.as_view(), name='delete_faculty'),

    path('CUS/form/upload/images', views.facutyimages, name='gallery_form'),
    path('CUS/gallery/', views.ImageList.as_view(), name='varsity_images'),

]

students/urls.py
from django.urls import path
from . import views
# from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),
    path('student/login/', views.student_login, name='student_login'),
    path('logout/', views.StudentLogoutView, name="student_logout"),

    path('change/<int:pk>/password/', views.change_password, name='change_password' ),


    path('<department_slug>/<student_slug>/profile/', views.StudentDetailView.as_view(), name='student_detail'),

    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.AccountEditView.as_view(), name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students')
]

New folder/faculty/models.py
# from django.db import models

# Create your models here.


from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
import misaka


class Faculty(models.Model):
    name = models.CharField(max_length=128, unique=True)
    dean = models.CharField(max_length=45, unique=True)
    detail = models.TextField()
    detail_html = models.TextField(editable=False)
    faculty_slug = models.SlugField(allow_unicode=True, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.faculty_slug = slugify(self.name)
        self.detail_html = misaka.html(self.detail)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("faculties:faculty_detail",
                        kwargs={'faculty_slug':self.faculty_slug})

    class Meta:
        ordering = ["name"]


def get_image_filename(instance, filename):
    name = instance.faculty.name
    slug = slugify(name)
    return "faculty_images/%s-%s" % (slug, filename)


class FacultyImages(models.Model):
    faculty = models.ForeignKey(Faculty,related_name='faculty_images', default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='faculty_image', blank=True)



class VarsityImages(models.Model):
    image = models.ImageField(upload_to='univerrsity/gallery', blank=True)

New folder/faculty/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Faculty, FacultyImages, VarsityImages

class FacultyForm(forms.ModelForm):
    class Meta():
        model = Faculty
        fields = ('name', 'dean', 'detail')


class FacultyImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = FacultyImages
        fields = ('image', )


class VarsityImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = VarsityImages
        fields = ('image',)

faculties/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Faculty, FacultyImages, VarsityImages

class FacultyForm(forms.ModelForm):
    class Meta():
        model = Faculty
        fields = ('name', 'detail',)


class FacultyImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = FacultyImages
        fields = ('image', )


class VarsityImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = VarsityImages
        fields = ('image',)

New folder/faculty/views.py
# from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404, redirect
# Extra Imports for the Login and Logout Capabilities
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import UserPassesTestMixin
from django.template import context
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory

from . models import Faculty, FacultyImages
from . forms import FacultyForm, FacultyImageForm



class SuperUserCheck(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser



@login_required
def CreateFaculty(request):
    if request.user.is_superuser:
        ImageFormSet = modelformset_factory(model=FacultyImages,
                                    form=FacultyImageForm, extra=3 )

        if request.method == 'POST':
            facultyForm = FacultyForm(request.POST)
            formset = ImageFormSet(request.POST, request.FILES,
                                queryset=FacultyImages.objects.none())

            if facultyForm.is_valid() and formset.is_valid():
                faculty_form = facultyForm.save(commit=False)
                faculty_form.user = request.user
                faculty_form.save()

                # faculty_form = faculty_form.cleaned_data()
                name = request.POST.get('name')
                from django.utils.text import slugify
                faculty_slug = slugify(name)

                for form in formset.cleaned_data:
                    #this helps to not crash if the user
                    #do not upload all the photos
                    if form:
                        image = form['image']
                        faculty_image = FacultyImages(faculty=faculty_form, image=image)
                        faculty_image.save()

                messages.success(request,
                            "Photos has been uploaded to faculties section of media!")
                return HttpResponseRedirect(reverse("faculties:faculty_detail", kwargs={"faculty_slug":faculty_slug}))
            else:
                print(facultyForm.errors, formset.errors)
        else:
            facultyForm = FacultyForm()
            formset = ImageFormSet(queryset=FacultyImages.objects.none())
        return render(request, 'faculties/faculty_form.html', {
                                "faculty_form":facultyForm,
                                "formset":formset
                            })
    else:
        return HttpResponse("You must be a superuser to create a faculty!")



class UpdateFaculty(SuperUserCheck, UpdateView):
    redirect_field_name = 'faculties/faculty_list.html'

    form_class = FacultyForm
    model = Faculty
    slug_field = 'faculty_slug'
    slug_url_kwarg = 'faculty_slug'

    template_name = 'faculties/faculty_update.html'


class FacultyList(ListView):
    model = Faculty
    template_name = 'faculties/faculty_list.html'


class FacultyDetail(DetailView):
    model = Faculty
    slug_field = 'faculty_slug'
    slug_url_kwarg = 'faculty_slug'
    template_name='faculties/faculty_detail.html'


class FacultyDelete(SuperUserCheck, DeleteView):
    success_url = reverse_lazy('faculties:faculty_list')
    model = Faculty
    slug_field = 'faculty_slug'
    slug_url_kwarg = 'faculty_slug'

    template_name='faculties/faculty_confirm_delete.html'


from . models import VarsityImages
from . forms import VarsityImageForm
@login_required
def facutyimages(request):
    ImageFormSet = modelformset_factory(model=VarsityImages,
                form=VarsityImageForm, extra=7)

    if request.method == 'POST':
        formset = ImageFormSet(request.POST, request.FILES,
                                queryset=VarsityImages.objects.none())

        if formset.is_valid():
            formset.save()
            messages.success(request,
                            "Photos has been uploaded to faculties section of media!")
            return HttpResponseRedirect(reverse("faculties:varsity_images"))
        else:
            print(FacultyForm.errors, formset.errors)
    else:
        formset = ImageFormSet(queryset=FacultyImages.objects.none())

    return render(request, 'faculties/gallery_form.html', {
                                "formset":formset
                            })


class ImageList(ListView):
    model = VarsityImages
    context_object_name = 'varsity_images'

    template_name = 'faculties/gallery.html'

faculties/views.py
# from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404, redirect
# Extra Imports for the Login and Logout Capabilities
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import UserPassesTestMixin
from django.template import context
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory

from . models import Faculty, FacultyImages
from . forms import FacultyForm, FacultyImageForm



class SuperUserCheck(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser



@login_required
def CreateFaculty(request):
    if request.user.is_superuser:
        ImageFormSet = modelformset_factory(model=FacultyImages,
                                    form=FacultyImageForm, extra=3 )

        if request.method == 'POST':
            facultyForm = FacultyForm(request.POST)
            formset = ImageFormSet(request.POST, request.FILES,
                                queryset=FacultyImages.objects.none())

            if facultyForm.is_valid() and formset.is_valid():
                faculty_form = facultyForm.save(commit=False)
                faculty_form.user = request.user
                faculty_form.save()

                # faculty_form = faculty_form.cleaned_data()
                name = request.POST.get('name')
                from django.utils.text import slugify
                faculty_slug = slugify(name)

                for form in formset.cleaned_data:
                    #this helps to not crash if the user
                    #do not upload all the photos
                    if form:
                        image = form['image']
                        faculty_image = FacultyImages(faculty=faculty_form, image=image)
                        faculty_image.save()

                messages.success(request,
                            "Photos has been uploaded to faculties section of media!")
                return HttpResponseRedirect(reverse("faculties:faculty_detail", kwargs={"faculty_slug":faculty_slug}))
            else:
                print(facultyForm.errors, formset.errors)
        else:
            facultyForm = FacultyForm()
            formset = ImageFormSet(queryset=FacultyImages.objects.none())
        return render(request, 'faculties/faculty_form.html', {
                                "faculty_form":facultyForm,
                                "formset":formset
                            })
    else:
        return HttpResponse("You must be a superuser to create a faculty!")



class UpdateFaculty(SuperUserCheck, UpdateView):
    redirect_field_name = 'faculties/faculty_list.html'

    form_class = FacultyForm
    model = Faculty
    slug_field = 'faculty_slug'
    slug_url_kwarg = 'faculty_slug'

    template_name = 'faculties/faculty_update.html'


class FacultyList(ListView):
    model = Faculty
    template_name = 'faculties/faculty_list.html'


class FacultyDetail(DetailView):
    model = Faculty
    slug_field = 'faculty_slug'
    slug_url_kwarg = 'faculty_slug'
    template_name='faculties/faculty_detail.html'


class FacultyDelete(SuperUserCheck, DeleteView):
    success_url = reverse_lazy('faculties:faculty_list')
    model = Faculty
    slug_field = 'faculty_slug'
    slug_url_kwarg = 'faculty_slug'

    template_name='faculties/faculty_confirm_delete.html'


from . models import VarsityImages
from . forms import VarsityImageForm
@login_required
def facutyimages(request):
    ImageFormSet = modelformset_factory(model=VarsityImages,
                form=VarsityImageForm, extra=7)

    if request.method == 'POST':
        formset = ImageFormSet(request.POST, request.FILES,
                                queryset=VarsityImages.objects.none())

        if formset.is_valid():
            formset.save()
            messages.success(request,
                            "Photos has been uploaded to faculties section of media!")
            return HttpResponseRedirect(reverse("faculties:varsity_images"))
        else:
            print(FacultyForm.errors, formset.errors)
    else:
        formset = ImageFormSet(queryset=FacultyImages.objects.none())

    return render(request, 'faculties/gallery_form.html', {
                                "formset":formset
                            })


class ImageList(ListView):
    model = VarsityImages
    context_object_name = 'varsity_images'

    template_name = 'faculties/gallery.html'

faculties/templates/faculties/faculty_base.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}

 <br><br><br>
 {% block content %}  {% endblock %}


{% endblock %}

faculties/templates/faculties/faculty_confirm_delete.html
{% extends "faculties/faculty_base.html" %}


{% block content %}

  <div class="container jumbotron">
    <form class="" method="post">
      {% csrf_token %}

      <h3>Do you want to delete <span><strong>{{ object }}</strong></span> ?</p>
      <input type="submit" class="btn btn-danger" value="Confirm Delete">
    </form>
  </div>


{% endblock %}

faculties/templates/faculties/faculty_detail.html
{% extends "faculties/faculty_base.html" %}
{% load static %}

{% block content %}

  <div class="container jumbotron">
    <h1>{{faculty.name}}</h1><br><br>
    {# <h2>Departments: {{faculty.departments.count }}</h2> #}
    <br>
    <h4>Dean: <span style="color:#50707a;">{{faculty.dean}}</span> </h4><br><br>
    <h5>{{faculty.detail_html|safe}}</h5><br>
    {% if user.is_superuser %}
      <a class="btn btn-lg btn-warning" href="{% url 'faculties:update_faculty' faculty_slug=faculty.faculty_slug %}">
        <span class="fa fa-times-circle-ok"></span> Update Faculty
      </a>

      <a class="btn btn-lg btn-danger" href="{% url 'faculties:delete_faculty' faculty_slug=faculty.faculty_slug %}">
        <span class="fa fa-times-circle-o"></span> Delete Faculty
      </a>
    {% endif %}
  </div>


<section id="portfolio" class="portfolio section-bg">

  {% if faculty.faculty_images.count != 0 %}
    <div class="container">
      <h5>Photos of {{faculty.name}}</h5><br>
      <div class="row portfolio-container" data-aos="fade-up">

        {% for img in faculty.faculty_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-faculty">
          <div class="portfolio-wrap">

                <img src='{{ img.image.url }}' class="img-fluid" alt="">
                <div class="portfolio-info">
                  <h4>{{ faculty.name }}</h4>

                <div class="portfolio-links">
                  <h5><a href='{{ img.image.url }}' data-gall="portfolioGallery" class="venobox"  title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
                </div>

              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

  {% else %}
    <div class="container">
      <h4>Faculty has no photos!</h3>
    </div>
  {% endif %}
  </section>



<br><br>
  <section id="steps" class="steps section-bg">
    <div class="container">
      <h4>Departments under {{faculty.name}}</h4>

      {% if faculty.departments.count == 0 %}
      <h5 style="color:blue;"><br>No departments in this group!</h3><br><br>

      {% else %}
        {% for department in faculty.departments.all %}
          <ul>
            <li><a href="{% url 'departments:department_detail' faculty_slug=faculty.faculty_slug department_slug=department.department_slug %}"> {{department.name}} </a> </li>
          </ul>
        {% endfor %}
      {% endif %}

      {% if  user.is_superuser  %}
      <a class="btn btn-lg btn-warning" href="{% url 'departments:create_department' %}">
        <span class="fa fa-times-circle-ok"></span> Create Department
      </a>
      {% endif %}
    </div>
  </section>


  <section id="portfolio" class="portfolio section-bg">

    <div class="container">
      <div class="row" data-aos="fade-up">
        <h5 style="text-align:center;">Photos of Departments</h3><br>
        <div class="col-lg-12 d-flex justify-content-center">

          <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">ALL</li>
            <li data-filter=".filter-app">{{ faculty.departments.all.0.acronyms }}</li>
            <li data-filter=".filter-web">{{ faculty.departments.all.1.acronyms }}</li>
            <li data-filter=".filter-card">{{ faculty.departments.all.2.acronyms }}</li>
          </ul>

        </div>
      </div>

      <div class="row portfolio-container" data-aos="fade-up">

        {% for department in faculty.departments.all %}

        {% if department.acronyms == faculty.departments.all.0.acronyms %}

        {% for img in department.department_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">

                  <img src='{{img.image.url}}' class="img-fluid" alt="">
                  <div class="portfolio-info">

                    <div class="portfolio-links">
                      <a href="{{img.image.url}}" data-gall="portfolioGallery" class="venobox"><i class="bx bx-link"></i>Full Picture</a>
                      <a href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}" title="Go to Departmentd"><i class="bx bx-link"></i>Go to {{department.acronyms}}</a>
                    </div>

                  </div>
            </div>
        </div>
        {% endfor %}

        {% elif department.acronyms == faculty.departments.all.1.acronyms %}
        {% for img in department.department_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">

                  <img src='{{img.image.url}}' class="img-fluid" alt="">
                  <div class="portfolio-info">

                  <div class="portfolio-links">
                    <a href="{{img.image.url}}" data-gall="portfolioGallery" class="venobox"><i class="bx bx-link"></i>Full Picture</a>
                    <a href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}" title="More Details"><i class="bx bx-link"></i>Go to {{department.acronyms}}</a>
                  </div>
              </div>
            </div>
        </div>
        {% endfor %}

        {% elif department.acronyms == faculty.departments.all.2.acronyms %}
        {% for img in department.department_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <div class="portfolio-wrap">

                <img src='{{img.image.url}}' class="img-fluid" alt="">
                <div class="portfolio-info">

                <div class="portfolio-links">
                  <a href="{{img.image.url}}" data-gall="portfolioGallery" class="venobox"><i class="bx bx-link"></i>Full Picture</a>
                  <a href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}" title="More Details"><i class="bx bx-link"></i>Go to {{department.acronyms}}</a>
                </div>

              </div>
          </div>
        </div>
        {% endfor %}

        {% else %}
        {% for img in department.department_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-extra">
            <div class="portfolio-wrap">

                <img src='{{img.image.url}}' class="img-fluid" alt="">
                <div class="portfolio-info">

                <div class="portfolio-links">
                  <a href="{{img.image.url}}" data-gall="portfolioGallery" class="venobox"><i class="bx bx-link"></i>Full Picture</a>
                  <a  href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}" title="More Details"><i class="bx bx-link"></i>Go to {{department.acronyms}}</a>
                </div>

                </div>

            </div>
        </div>
        {% endfor %}

        {% endif %}

        {% endfor %}
      </div>

    </div>

  </section>

{% endblock %}

faculties/templates/faculties/faculty_form.html
{% extends "faculties/faculty_base.html" %}
{% load bootstrap4 %}

{% block content %}

<section id="steps" class="steps section-bg">
  <div class="container">
    <form id="faculty_form" method="post" action="" enctype="multipart/form-data">

      {% csrf_token %}


      {% bootstrap_form faculty_form %}

      {{ formset.management_form }}
      {% for form in formset %}
          {{ form }} <br> <br>
      {% endfor %}
      <br>

      <input type="submit" name="submit" value="Create Faculty" />
    </form>

  </div>

</section>


{% endblock %}

faculties/templates/faculties/faculty_list.html
{% extends "faculties/faculty_base.html" %}

{% block content %}

  <section id="steps" class="steps section-bg">
    <div class="container ">

      <h1>Faculties of Sikkim University</h1>

      <h4>Total facuties : {{faculty_list.count}} <br><br></h4>

      {% for faculty in faculty_list  %}

        <ul>
          <li><h5><a href="{% url 'faculties:faculty_detail' faculty_slug=faculty.faculty_slug %}">{{ faculty.name }}</a> </h1></li>
          <h6>Total Departments: {{faculty.departments.count }}</h2>
            <br>
        </ul>

      {% endfor %}
    </div>
  </section>


  <section id="portfolio" class="portfolio section-bg">

    <div class="container">
      <div class="row" data-aos="fade-up">
        <div class="col-lg-12 d-flex justify-content-center">

          <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">ALL</li>
            <li data-filter=".filter-app">{{ faculty_list.0 }}</li>
            <li data-filter=".filter-web">{{ faculty_list.1 }}</li>
            <li data-filter=".filter-card">{{ faculty_list.2 }}</li>
          </ul>

        </div>
      </div>

      <div class="row portfolio-container" data-aos="fade-up">
        {% for faculty in faculty_list %}

        {% if faculty ==  faculty_list.0  %}
        {% for img in faculty.faculty_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">
              <img src='{{ img.image.url }}' class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4>{{ faculty.name }}</h4>

                <div class="portfolio-links">
                  <a href="{% url 'faculties:faculty_detail' faculty_slug=faculty.faculty_slug %}" title="More Details"><i class="bx bx-link"></i>Detail</a>
                  <h5><a href='{{ img.image.url }}' data-gall="portfolioGallery" class="venobox"  title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
                </div>

              </div>
            </div>
        </div>
        {% endfor %}

        {% elif faculty == faculty_list.1 %}
        {% for img in faculty.faculty_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">

                  <img src='{{ img.image.url }}' class="img-fluid" alt="">
                  <div class="portfolio-info">
                    <h4>{{ faculty.name }}</h4>

                    <div class="portfolio-links">
                      <a href="{% url 'faculties:faculty_detail' faculty_slug=faculty.faculty_slug %}" title="More Details"><i class="bx bx-link"></i>Detail</a>
                      <h5><a href='{{ img.image.url }}' data-gall="portfolioGallery" class="venobox"  title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
                    </div>

                  </div>
            </div>
        </div>
        {% endfor %}

        {% elif faculty == faculty_list.2 %}
        {% for img in faculty.faculty_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <div class="portfolio-wrap">

                  <img src='{{ img.image.url }}' class="img-fluid" alt="">
                  <div class="portfolio-info">
                    <h4>{{ faculty.name }}</h4>

                    <div class="portfolio-links">
                      <a href="{% url 'faculties:faculty_detail' faculty_slug=faculty.faculty_slug %}" title="More Details"><i class="bx bx-link"></i>Detail</a>
                      <h5><a href='{{ img.image.url }}' data-gall="portfolioGallery" class="venobox"  title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
                    </div>

                  </div>
            </div>
        </div>
        {% endfor %}

        {% else %}
        {% for img in faculty.faculty_images.all %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-none">
            <div class="portfolio-wrap">

                <img src='{{ img.image.url }}' class="img-fluid" alt="">
                <div class="portfolio-info">
                  <h4>{{ faculty.name }}</h4>

                <div class="portfolio-links">
                  <a href="{% url 'faculties:faculty_detail' faculty_slug=faculty.faculty_slug %}" title="More Details"><i class="bx bx-link"></i>Detail</a>
                  <h6><a href='{{ img.image.url }}' data-gall="portfolioGallery" class="venobox"  title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>

                </div>

                </div>

          </div>
        </div>
        {% endfor %}

        {% endif %}
        {% endfor %}
      </div>
    </div>

  </section>

{% endblock %}