UniversityWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('about/', views.about),
#     path('', views.homepage, name='index'),
#     path('contact_us/', views.contact_us, name='contact_us'),
#     # path('students/', include('students.urls')),
#     path('faculties/', include("faculties.urls")),
#     path('departments/', include("departments.urls")),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.AllFacultyList.as_view() , name='index'),
    # path('contact_us/', views.contact_us, name='contact_us'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('faculties/', include("faculties.urls", namespace="faculties")),
    path('departments/', include("departments.urls", namespace='departments')),
    path('students/', include("students.urls", namespace='students')),
    path('teachers/', include("teachers.urls", namespace='teachers')),

    # re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

departments/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
#from django.conf.urls import url
app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('CUS/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('CUS/<faculty_slug>/edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('CUS/<faculty_slug>/<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('CUS/<faculty_slug>/department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

faculties/urls.py
from django.urls import path
from . import views



app_name = 'faculties'


urlpatterns = [
    path('create/new/faculty/', views.CreateFaculty, name='create_faculty'),

    path('CUS/<faculty_slug>/edit/', views.UpdateFaculty.as_view(), name='update_faculty'),

    path('CUS/all/', views.FacultyList.as_view(), name='faculty_list'),
    path('CUS/<faculty_slug>/departments/', views.FacultyDetail.as_view(), name='faculty_detail'),
    path('CUS/<faculty_slug>/delete', views.FacultyDelete.as_view(), name='delete_faculty'),

    path('CUS/form/upload/images', views.facutyimages, name='gallery_form'),
    path('CUS/gallery/', views.ImageList.as_view(), name='varsity_images'),

]

students/urls.py
from django.urls import path
from . import views
# from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),
    path('student/login/', views.student_login, name='student_login'),
    path('logout/', views.StudentLogoutView, name="student_logout"),

    path('change/<int:pk>/password/', views.change_password, name='change_password' ),


    path('<department_slug>/<student_slug>/profile/', views.StudentDetailView.as_view(), name='student_detail'),

    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.AccountEditView.as_view(), name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students')
]

teachers/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('teacher/register/', views.teacher_register, name='teacher_register'),
    path('teacher_login/', views.teacher_login, name='teacher_login'),
    path('logout/', views.TeacherLogoutView , name="teacher_logout"),

    path('change/<teacher_slug>/password/', views.change_password, name='change_password' ),

    path('department/<department_slug>/profile/<teacher_slug>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('department/<department_slug>/teachers', views.TeacherList.as_view(), name='teacher_list'),
    path('update/profile/teacher/<teacher_slug>/', views.TeacherAccountEditView.as_view(), name='update_teacher_profile'),
    path('delete/<department_slug>/teacher/<teacher_slug>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),

    path('all/teachers/', views.AllTeachers.as_view(), name='all_teachers')
]

teachers/models.py
# from django.db import models

# Create your models here.


from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
import misaka
from departments.models import Department

teacher_rank = [
    ("Lecturer", "Lecturer"),
    ("Assistant professor", "Assistant professor"),
    ("Associate professor", "Associate professor"),
    ("Professor", "Professor"),
    ("Professor emeritus", "Professor emeritus"),
]

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    department = models.ForeignKey(Department,blank=False, related_name="teachers", on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='teachers/profile_pics', blank=True)
    Teacher_ID = models.CharField(max_length=20, unique=True, blank=False)
    portfolio_site = models.URLField(blank=True)
    academic_rank = models.CharField(blank=False, max_length=100, choices=teacher_rank)
    teacher_slug = models.SlugField(allow_unicode=True, unique=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.teacher_slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("teachers:teacher_detail",
                        kwargs={"department_slug":self.department.department_slug,
                            "teacher_slug":self.teacher_slug})

    class Meta:
        ordering = ["Teacher_ID"]
        unique_together = ["Teacher_ID", "department"]

teachers/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Teacher

class TeacherForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    Confirm_Password = forms.CharField(label='confirm your password',widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(TeacherForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("Confirm_Password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class TeacherProfileInfoForm(forms.ModelForm):
    class Meta():
        model = Teacher
        fields = ('Teacher_ID' ,'department', 'academic_rank', 'portfolio_site', 'profile_pic')

teachers/views.py
# from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect,get_object_or_404

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin

from django.forms import ModelForm
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory

from .forms import TeacherForm, TeacherProfileInfoForm
from .models import Teacher
from departments.models import Department

@login_required
def TeacherLogoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def teacher_register(request):
    registered = False

    if request.method == 'POST':
        teacher_form = TeacherForm(data=request.POST)
        teacher_profile_form = TeacherProfileInfoForm(data=request.POST)

        if teacher_form.is_valid() and teacher_profile_form.is_valid():
            # Save User Form to Database
            user = teacher_form.save()

            # Hash the password
            user.set_password(user.password)
            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!
            # Can't commit yet because we still need to manipulate
            teacher_profile = teacher_profile_form.save(commit=False)
            # Set One to One relationship between
            # TeacherForm and TeacherProfileInfoForm
            teacher_profile.user = user

            if 'profile_pic' in request.FILES:
                teacher_profile.profile_pic = request.FILES['profile_pic']

            # now saving the model
            teacher_profile.save()
            registered = True

            name = request.POST.get('username')
            dept_id=request.POST.get('department')
            # get_object_or_404(Group,slug=self.kwargs.get("slug"))
            department = get_object_or_404(Department, pk=dept_id)
            from django.utils.text import slugify
            teacher_slug = slugify(name)
            dept_slug = slugify(department.name)
            print("\n\n****department: {} and teacher: {}***/n/n".format(dept_slug, teacher_slug))

            return HttpResponseRedirect(reverse('teachers:teacher_detail',
                                kwargs={'department_slug':dept_slug,
                                        'teacher_slug':teacher_slug}))
        else:
            print(teacher_form.errors, teacher_profile_form.errors)
    else:
        teacher_form = TeacherForm()
        teacher_profile_form = TeacherProfileInfoForm()

    return render(request, "teachers/teacher_registration.html",context={
                    'teacher_form':teacher_form,
                    'teacher_profile_form':teacher_profile_form,
                    'registered':registered})


def teacher_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")

        else :
            print('Invalid Username: {} and password: {} is provided'.format(username, password))
            return HttpResponse("Invalid username or password supplied!")
    else:
        return render(request, 'teachers/login.html',{})


@login_required
def change_password(request):
    if request.mathod == 'POST':
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password is changed!")
            logout(request)
            return redirect('teachers:teacher_login')
        else:
            messages.error(request, "Please provide valid information")
    else:
        form = PasswordChangeForm(request, user)
    return render(request, 'teachers/change_password.html',{
                            'form':form})


class TeacherDetailView(SelectRelatedMixin, DetailView):
    select_related = ("user", "department")
    context_object_name = 'teacher_detail'
    model = Teacher
    template_name = 'teachers/teacher_detail.html'

    def get_object(self):
        return get_object_or_404(
            Teacher,
            teacher_slug=self.kwargs['teacher_slug']
            # access_key=self.kwargs['access_key'],
        )


class TeacherList(SelectRelatedMixin, ListView):
    model = Teacher
    select_related = ("user", "department")

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['slug'] = self.kwargs['slug']
    #     # context['current_month'] = self.current_month
    #     return context


class TeacherUpdateView(InlineFormSetFactory):
    model = Teacher
    fields = ['profile_pic','department', 'portfolio_site','academic_rank']

class TeacherAccountEditView(UpdateWithInlinesView):
    model = User
    fields = ['username', 'email', 'password']
    inlines = [TeacherUpdateView,]
    template_name = 'teachers/profileupdate_form.html'
    old_password = [] 
    old_password.clear()

    def get_object(self):
        user = User.objects.get(pk=self.request.user.pk)
        self.old_password.append(user.password)
        return user

    def get_success_url(self):
        user1 = self.get_object()
        if self.old_password[1] == self.old_password[2]:
            print("no change passsword ",user1.password)
        else:
            user1.set_password(user1.password)
            print("password changed")

        user1.save()
        user1.teacher.save()
        self.old_password.clear()

        return get_object_or_404(
                    Teacher,
                    pk=user1.teacher.id
                ).get_absolute_url()


class TeacherUpdateView(LoginRequiredMixin,SelectRelatedMixin,  UpdateView):
    login_url = '/teacher/login/'
    select_related = ("user", "department")
    redirect_field_name = '/department/<department_slug>/profile/<teacher_slug>/'

    fields = ("username","password", "profile_pic")
    model = Teacher
    template_name = 'teachers/profileupdate_form.html'


class TeacherDeleteView(LoginRequiredMixin,SelectRelatedMixin, DeleteView):
    login_url = '/teacher/login/'
    redirect_field_name = 'blog/post_detail.html'
    model = Teacher
    select_related = ("user", "department")

    def get_object(self):
        return Teacher.objects.get(teacher_slug=self.kwargs['teacher_slug'])

    def get_success_url(self):
          # if you are passing 'slug' from 'urls' to 'DeleteView' for teacher
          # capture that 'slug' as dept_slug and pass it to 'reverse_lazy()' function
          dept_slug = self.kwargs['department_slug']
          teacher_slug = self.kwargs['teacher_slug']

          teacher = self.get_object()
          user = teacher.user
          logout(self.request)
          user.delete()
          return reverse_lazy('departments:department_teachers', kwargs={
                                    'department_slug': dept_slug, })



class AllTeachers(ListView):
    model = Teacher
    context_object_name = "teachers"
    template_name = 'teachers/all_teachers.html'




#

teachers/templates/teachers/_teacher.html
<div class="media">

	<div class="media-body">
		<strong><a href="{% url 'teachers:teacher_detail' department_slug=teacher.department.department_slug teacher_slug=teacher.teacher_slug %}"> {{ teacher.user.username }}</a> </strong>

    <ol>
			<li> {{ teacher.user.username  }} </li>
      <li> {{ teacher.teacher_ID  }} </li>
      <li> {{ teacher.email  }} </li>
      <li> <a href="{% url 'departments:detail' faculty_slug=teacher.department.faculty.faculty_slug department_slug=teacher.department.department_slug %}">{{ teacher.department.name }}</a> </li>
      <li> <a href="{% url 'faculties:detail' slug=teacher.department.faculty.slug %}">{{ teacher.department.faculty.name }}</a> </li>

    </ol>


		<div class="media-footer">
			{% if user.is_superuser %}
				<a href="{% url 'teachers:teacher_delete' department_slug=teacher.department.department_slug teacher_slug=teacher.teacher_slug %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

teachers/templates/teachers/all_teachers.html
{% extends "teachers/teacher_base.html" %}

{% block content %}

  <div class="container jumbotron">

    <h3>Welcome to Teachers page</h3>
    <h5>Teachers are listed below</h5>
    <h6>Total teachers in UIT: {{teachers.count}}</h6>

    <br><br>
    <h6><span style="font-weight:bold">Total teachers:</span> {{department.teachers.count }}</h2>

    <br>

  </div>


  <div >
    <section id="steps" class="container steps section-bg" style="background-color:#fafcff">


      <table id="details_table" align="center">
        <thead style="color:blue">
          <th>Profile Pic</th>
          <th> <p>Username </p> </th>
          <th> <p>Academic Rank</p> </th>
          <th> <p>Teacher ID</p> </th>
          <th> <p>Email</p> </th>
          <th><p>Department</p> </th>

        </thead>
        <tr >
          <td class="extra-row"><br> </td>
          <td class="extra-row"><br> </td>
        </tr>

        {% for teacher in teachers %}
        <tr>
          {% if teacher.profile_pic %}
           <td><img src="{{ teacher.profile_pic.url }}"  height=150 width=150 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=150 width=150 alt=""></td>
          {% endif %}

          <td><p> <a href="{% url 'teachers:teacher_detail' department_slug=teacher.department.department_slug teacher_slug=teacher.teacher_slug %} " style="color:#1bac91; font-size:19px"> {{teacher.user.username}}</a> </h4></td>
          <td> {{teacher.academic_rank}} </td>
          <td> {{ teacher.Teacher_ID }} </td>

          {% if teacher.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{teacher.user.email}}</p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</p> </td>
          {% endif %}

          <td> {{ teacher.department.acronyms }} </td>
          <td><p> <span style="color:#2f5b9c;">{{teacher.session}}</p> </td>
        </tr>
        <tr >
          <td class="extra-row"><br> </td>
        </tr>
        <tr >
        </tr>
        {% endfor %}
      </table>


    </section>
  </div>

<br><br><br>

{% endblock %}

teachers/templates/teachers/change_password.html
{% extends "teachers/teacher_base.html" %}
{% load bootstrap4 %}
{% block content %}
<form class="" action="index.html" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}

  {{form}}

  {% buttons %}
    <button class="btn btn-primary" type="submit" name="button">Change Password</button>
  {% endbuttons %}
</form>

{% endblock %}

teachers/templates/teachers/profileupdate_form.html
{% extends "teachers/teacher_base.html" %}
{% load bootstrap4 %}

{% block content %}
<section id="steps" class="steps section-bg">
  <div class="container">

    <form  method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% bootstrap_form form %}

      {% for formset in inlines %}
        <br>{{ formset.as_p }}<br>
      {% endfor %}

      {% buttons %}
        <button class="btn btn-primary" type="submit" name="button">Update Profile</button>
      {% endbuttons %}
    </form>

  </div>
</section>
{% endblock %}

teachers/templates/teachers/teacher_base.html
{% extends "base.html" %}

{% block body_block %}
<br><br><br>

{% block content %}  {% endblock %}

{% endblock %}

teachers/templates/teachers/teacher_confirm_delete.html
{% extends "teachers/teacher_base.html" %}

{% block content %}
<div class="contaier jumbotron">
	<h3>Are you sure you want to delete {{object.name}}?</h3>

	<form method="POST">
		{% csrf_token %}
		<br><br>
		<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
		<a href="{% url 'teachers:teacher_detail' department_slug=teacher.department.department_slug teacher_slug=teacher.teacher_slug %}" class="btn btn-light btn-large">Cancel</a>
		<br><br>
	</form>
</div>

{% endblock %}

teachers/templates/teachers/teacher_detail.html
{% extends "teachers/teacher_base.html" %}
{% block content %}


<section id="portfolio" class="portfolio section-bg">

<div class="container">
  <h1>Welcome to the Teacher Detail Page</h1><br><br>
  <div class="row portfolio-container" data-aos="fade-up">
    <div class="col-lg-4 col-md-6 portfolio-item filter-faculty">
      <div class="portfolio-wrap">
            {% if teacher_detail.profile_pic %}
             <img class="img-fluid" src="{{ teacher_detail.profile_pic.url }}" alt="">

             <div class="portfolio-info">
               <h4>{{ faculty.name }}</h4>

             <div class="portfolio-links">
               <h5><a href='{{ teacher_detail.profile_pic.url }}' title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
             </div>

           </div>

            {% else %}
              <img class="img-fluid"  src="/static/no_profile_pic.png" alt="">
            {% endif %}

      </div>
    </div>

    <div class="col-lg-8 col-md-6 portfolio-item filter-faculty">
      <table id="details_table_teacher">
        <tr>
          <td> <p>Teacher Name: </p> </td>
          <td><p><span style="color:#2f5b9c;">{{teacher_detail.user.username}}</span></p> </td>
        </tr>

        <tr>
          <td> <p>Academic Rank: </p> </td>
          <td><p><span style="color:#2f5b9c;">{{teacher_detail.academic_rank}}</span></p> </td>
        </tr>

        <tr>
          <td> <p>Teacher ID: </td>
          <td> <span style="color:#2f5b9c;">{{teacher_detail.Teacher_ID}}</p> </td>
        </tr>

        <tr>
          <td> <p>Email: </td>
          {% if teacher_detail.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{teacher_detail.user.email}}</p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</p> </td>
          {% endif %}
        </tr>

        <tr>
          <td> <p>Department:  </td>
          <td><span style="color:#2f5b9c;"><a href="{% url 'departments:department_detail' faculty_slug=teacher_detail.department.faculty.faculty_slug department_slug=teacher_detail.department.department_slug %}">{{teacher_detail.department}}</a>  </td>
        </tr>

        <tr>
          <td><p>Faculty: </td>
          <td> <span style="color:#2f5b9c;"><a href="{% url 'faculties:faculty_detail' faculty_slug=teacher_detail.department.faculty.faculty_slug %}">{{teacher_detail.department.faculty}}</a> </p></td>
        </tr>

        <tr>
          <td><p>Portfolio Site </p> </td>
          <td><a href="{{teacher_detail.portfolio_site}}"> <span style="color:#2f5b9c;">{{teacher_detail.portfolio_site}}</a> </td>
        </tr>
      </table>


      </div>


    </div>

  </div>
</div>
</section>


{% if user.is_authenticated and user.username == teacher_detail.user.username %}
<br><br>
<div class="container">
  <a class='btn btn-warning' href="{% url 'teachers:update_teacher_profile' teacher_slug=teacher_detail.teacher_slug %}">
    <span class="fa fa-times-circle-ok"></span> Update Profile</a>
  <a class='btn btn-danger' href="{% url 'teachers:delete_teacher' department_slug=teacher_detail.department.department_slug teacher_slug=teacher_detail.teacher_slug %}">
    <span class="fa fa-times-circle-ok"></span> Delete Profile</a>

</div>
{% endif %}
<br><br>



{% endblock %}

teachers/templates/teachers/teacher_list.html
{% extends "teachers/teacher_base.html" %}
{% load humanize %}

{% block content %}


<div class="">
	{% for teacher in teacher_list %}
  {% include "teachers/_teacher.html" %}
	{% endfor %}
</div>


{% endblock %}

teachers/templates/teachers/teacher_registration.html
{% extends "teachers/teacher_base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

  <div class="container">
    <div class="jumbotron">

      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}

        <h1>Register Here</h1>
        <h3>Fill up Teacher registration form</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {% bootstrap_form teacher_form %}
          {% bootstrap_form teacher_profile_form %}

          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}