UniversityWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('about/', views.about),
#     path('', views.homepage, name='index'),
#     path('contact_us/', views.contact_us, name='contact_us'),
#     # path('students/', include('students.urls')),
#     path('faculties/', include("faculties.urls")),
#     path('departments/', include("departments.urls")),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.AllFacultyList.as_view() , name='index'),
    # path('contact_us/', views.contact_us, name='contact_us'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('faculties/', include("faculties.urls", namespace="faculties")),
    path('departments/', include("departments.urls", namespace='departments')),
    path('students/', include("students.urls", namespace='students')),
    path('teachers/', include("teachers.urls", namespace='teachers')),

    # re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

departments/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
#from django.conf.urls import url
app_name = "departments"


urlpatterns = [
    path('create/new/', views.CreateDepartment , name='create_department'),
    path('CUS/all/departments/', views.AllDepartments.as_view(), name='all_departments'),

    path('CUS/<faculty_slug>/edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('CUS/<faculty_slug>/<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),

    path('CUS/<faculty_slug>/department/<department_slug>/delete', views.DepartmentDelete.as_view(), name='delete_department'),

    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students' ),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers' ),

]

faculties/urls.py
from django.urls import path
from . import views



app_name = 'faculties'


urlpatterns = [
    path('create/new/faculty/', views.CreateFaculty, name='create_faculty'),

    path('CUS/<faculty_slug>/edit/', views.UpdateFaculty.as_view(), name='update_faculty'),

    path('CUS/all/', views.FacultyList.as_view(), name='faculty_list'),
    path('CUS/<faculty_slug>/departments/', views.FacultyDetail.as_view(), name='faculty_detail'),
    path('CUS/<faculty_slug>/delete', views.FacultyDelete.as_view(), name='delete_faculty'),

    path('CUS/form/upload/images', views.facutyimages, name='gallery_form'),
    path('CUS/gallery/', views.ImageList.as_view(), name='varsity_images'),

]

students/urls.py
from django.urls import path
from . import views
# from django.conf.urls import url

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),
    path('student/login/', views.student_login, name='student_login'),
    path('logout/', views.StudentLogoutView, name="student_logout"),

    path('change/<int:pk>/password/', views.change_password, name='change_password' ),


    path('<department_slug>/<student_slug>/profile/', views.StudentDetailView.as_view(), name='student_detail'),

    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.AccountEditView.as_view(), name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students')
]

teachers/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('teacher/register/', views.teacher_register, name='teacher_register'),
    path('teacher_login/', views.teacher_login, name='teacher_login'),
    path('logout/', views.TeacherLogoutView , name="teacher_logout"),

    path('change/<teacher_slug>/password/', views.change_password, name='change_password' ),

    path('department/<department_slug>/profile/<teacher_slug>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('department/<department_slug>/teachers', views.TeacherList.as_view(), name='teacher_list'),
    path('update/profile/teacher/<teacher_slug>/', views.TeacherAccountEditView.as_view(), name='update_teacher_profile'),
    path('delete/<department_slug>/teacher/<teacher_slug>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),

    path('all/teachers/', views.AllTeachers.as_view(), name='all_teachers')
]

departments/models.py
# from django.db import models

# Create your models here.


from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from datetime import datetime
# Create your models here.
import misaka
from faculties.models import Faculty


class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    chairman = models.CharField(max_length=45, unique=True)
    detail = models.TextField()
    detail_html = models.TextField(editable=False)
    department_slug = models.SlugField(allow_unicode=True, unique=True)
    acronyms = models.CharField(max_length=10)
    # established_date = models.DateTimeField(blank=False, default=datetime.now())

    faculty = models.ForeignKey(Faculty, related_name="departments", on_delete=models.CASCADE)

    # immages = models.ManyToManyField(DepartmentImages,through=...)

    def __str__(self):
        return self.name.upper()

    def save(self, *args, **kwargs):
        self.department_slug = slugify(self.name)
        self.detail_html = misaka.html(self.detail)

        self.name = self.name.upper()
        self.acronyms = self.name.replace("&", "").replace("AND", "").replace("OF", "")
        self.acronyms = "".join(ch[0] for ch in self.acronyms.split())
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("departments:department_detail",
                        kwargs={"faculty_slug":self.faculty.faculty_slug ,
                                "department_slug":self.department_slug})

    class Meta:
        ordering = ["name"]


def get_image_filename(instance, filename):
    name = instance.department.name
    slug = slugify(name)
    return "department_images/%s-%s" % (slug, filename)


class DepartmentImages(models.Model):
    department = models.ForeignKey(Department,related_name='department_images', default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='department_image')

departments/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Department, DepartmentImages

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ('name', 'chairman', 'detail', 'faculty')
        # fields = ('name', 'chairman', 'detail', 'established_date')


class DepartmentImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = DepartmentImages
        fields = ('image', )

departments/views.py
# from django.shortcuts import render

# Create your views here.


from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import datetime

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.forms import modelformset_factory
from django.contrib import messages

from . models import DepartmentImages, Department
from faculties.models import Faculty
from . forms import DepartmentForm, DepartmentImageForm
from django.contrib.auth.mixins import UserPassesTestMixin


class SuperUserCheck(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser



@login_required
def CreateDepartment(request):
    ImageFormSet = modelformset_factory(model=DepartmentImages,
                                form=DepartmentImageForm, extra=3 )

    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                            queryset=DepartmentImages.objects.none())

        if departmentForm.is_valid() and formset.is_valid():
            department_form = departmentForm.save(commit=False)
            department_form.user = request.user
            department_form.save()

            dept_name = request.POST.get('name')
            # faculty_id=request.POST.get('faculty')
            # get_object_or_404(Group,slug=self.kwargs.get("slug"))
            #faculty = get_object_or_404(Faculty, pk=faculty_id)
            from django.utils.text import slugify
            dept_slug = slugify(dept_name)
            faculty_slug = slugify(Faculty.name)

            for form in formset.cleaned_data:
                #this helps to not crash if the user
                #do not upload all the photos
                if form:
                    image = form['image']
                    department_image = DepartmentImages(department=department_form, image=image)
                    department_image.save()

            messages.success(request,
                        "Photos has been uploaded to departments section of media!")
            print("\n\n****faculty: {} and dept: {}***/n/n".format(faculty_slug, dept_slug))
            return HttpResponseRedirect(reverse("departments:department_detail", kwargs={"faculty_slug":faculty_slug,
                                                                "department_slug":dept_slug}))
        else:
            print(departmentForm.errors, formset.errors)
    else:
        departmentForm = DepartmentForm()
        formset = ImageFormSet(queryset=DepartmentImages.objects.none())
    return render(request, 'departments/department_form.html', {
                            "department_form":departmentForm,
                            "formset":formset
                        })



class DepartmentDetail(DetailView):
    model = Department

    def get_object(self):
        return get_object_or_404(
            Department,
            department_slug__iexact=self.kwargs['department_slug'],
            # access_key=self.kwargs['access_key'],
        )


class DepartmentStudents(DetailView):
    model = Department
    slug_field = 'department_slug'
    slug_url_kwarg = 'department_slug'
    template_name = 'departments/department_students.html'


class DepartmentTeachers(DetailView):
    model = Department
    slug_field = 'department_slug'
    slug_url_kwarg = 'department_slug'
    template_name = 'departments/department_teachers.html'



class UpdateDepartment(SuperUserCheck, UpdateView):

    # def get_redirect_url(self):
    #     return reverse_lazy("departments:department_detail", kwargs={
    #                     "faculty_slug":self.kwargs['faculty_slug'],
    #                     "department_slug":self.kwargs['department_slug']
    #                             })

    def get_object(self):
        return get_object_or_404(
            Department,
            department_slug__iexact=self.kwargs['department_slug'],
            # access_key=self.kwargs['access_key'],
        )

    model = Department
    fields = ('chairman', 'detail')
    template_name = 'departments/department_update.html'



# class DepartmentList(ListView):
#     model = Department


class DepartmentDelete(SuperUserCheck, DeleteView):
    model = Department

    def get_success_url(self):
          # if you are passing 'slug' from 'urls' to 'DeleteView' for teacher
          # capture that 'slug' as dept_slug and pass it to 'reverse_lazy()' function
          Faculty_slug = self.kwargs['faculty_slug']
          return reverse_lazy('faculties:faculty_detail', kwargs={
                                    'faculty_slug': Faculty_slug,
                                    })

    def get_object(self):
        return get_object_or_404(
            Department,
            department_slug__iexact=self.kwargs['department_slug'],
            # access_key=self.kwargs['access_key'],
        )

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Department Deleted")
        return super().delete(*args, **kwargs)


class AllDepartments(ListView):
    model = Department









###########

departments/templates/departments/department_base.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}

 <br><br><br>
 {% block content %}  {% endblock %}


{% endblock %}

departments/templates/departments/department_confirm_delete.html
{% extends "departments/department_base.html" %}

{% block content %}
<section id="steps" class="steps section-bg">
	<div class="container">
		<h3>Are you sure you want to delete <span style="color:#1bac91; font-size:22px">{{object.name}}</span>?</h3><br><br>

		<form method="POST">
			{% csrf_token %}

			<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
			<a href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}" class="btn btn-primary btn-large">Cancel</a>

		</form>
	</div>
</section>

{% endblock %}

departments/templates/departments/department_detail.html
{% extends "faculties/faculty_base.html" %}

{% block content %}

  <div class="container jumbotron">
    <h2>Welcome to department detail page!</h2>
    <h2>Faculty: <a href="{% url 'faculties:faculty_detail' faculty_slug=department.faculty.faculty_slug %}"><span style="color:#1bac91;"> {{department.faculty.name}}</a> </span> </h1>
    <br> <ul>
      <h6>Total students: {{department.students.count }}</h2>
      <h6>Faculty members : {{department.teachers.count }}</h4>
    </ul>
    <br>
    <ul>
      <div class="row">
        <div class="col-lg-3 col-md-3">
          <h5><a class="btn btn-primary" href="{% url 'departments:department_teachers' department_slug=department.department_slug %}">Department Teachers</a> </h5>
        </div>
        <div class="col-lg-3 col-md-3">
          <h5><a class="btn btn-warning" href="{% url 'departments:department_students' department_slug=department.department_slug %}">Department Students</a> </h5>
        </div>
      </div>
    </ul>


    {% if user.is_superuser %}
    <ul>
      <div class="row">
        <div class="col-lg-3 col-md-3">
          <a class="btn btn-lg btn-primary" href="{% url 'departments:update_department' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}">
            <span class="fa fa-times-circle-ok"></span> Update Department
          </a>
        </div>

      <div class="col-lg-3 col-md-3">
        <a class="btn btn-lg btn-danger" href="{% url 'departments:delete_department' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}">
          <span class="fa fa-times-circle-o"></span> Delete Department
        </a>
      </div>
      </div>
    </ul>
    {% endif %}
  </div>

<div class="container">
  <h4>Name of the Department: <span style="color:#1bac91; font-size:19px">{{department.name}}</span> </h1>
  <ul>
    <li><h6>Acronym: {{department.acronyms}}</h2> </li>
    <li> <h6> Chairman : {{department.chairman}} </h3> </li>

    <li><h6>Total teachers : {{department.teachers.count}} </h2></li>
    <li><h6>Total students : {{department.students.count}} </h2></li>
    {% if department.established_date %}
      <li> <h6>Established at: {{department.established_date|time:"TIME_FORMAT"}}</h2> </li>
    {% endif %}
  </ul>
  <br><br>

  <br>
  <h5 style="color:#8a5030 ;"><strong>About {{department.name}}: </strong> </h5>
  <p style="color:#5c5b5a ;"> {{department.detail_html|safe}}</h4><br><br>
</div>


<section id="portfolio" class="portfolio section-bg">

    <div class="container">
      <div class="row portfolio-container" data-aos="fade-up">
        {% if department.department_images.count != 0 %}
        {% for img in department.department_images.all %}

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">

              <img src='{{ img.image.url }}' class="img-fluid" alt="">
              <div class="portfolio-info">
                <h4>{{ department.name }}</h4>

                <div class="portfolio-links">
                  <a href="{{img.image.url}}" data-gall="portfolioGallery" class="venobox"><i class="bx bx-link"></i>Full Picture</a>
                </div>
              </div>

            </div>
        </div>
      {% endfor %}

      {% else %}
      <h5>No photos uploaded in <span style="color:#1bac91;">{{department.name}}</span>. This site is under
        maintenance.</h2>
      {% endif %}
    </div>
  </div>
  </section>

<br><br><br><br>



{% endblock %}

departments/templates/departments/department_form.html
{% extends "departments/department_base.html" %}
{% load bootstrap4 %}

{% block content %}

<section id="steps" class="steps section-bg">
  <div class="container">
    {% if user.is_superuser %}
    <form id="department_form" method="post" action="" enctype="multipart/form-data">

      {% csrf_token %}


      {% for hidden in department_form.hidden_fields %}
          {{ hidden }}<br>
      {% endfor %}

      {% bootstrap_form department_form %}

      <br>
      {{ formset.management_form }}
      {% for form in formset %}
          {{ form }}<br><br>
      {% endfor %}

      <br>
      <input type="submit" name="submit" value="Create Department" />
    </form>
    {% else %}
    <h2>You must be a superuser to Create Department</h2>
    {% endif %}
  </div>
</section>
<br><br>
{% endblock %}

departments/templates/departments/department_list.html
{% extends "departments/department_base.html" %}

{% block content %}


<section id="steps" class="steps section-bg">
  <div class="container jumbotron">
    {% if department_list.count == 0 %}
      <h4>No departments created till now. This site is under construction.</h4>
    {% else %}
      <h4>Welcome to All department page of Sikkim University</h4>
      <h5>Number of departments : {{department_list.count}}</h5>
  </div>

  <div class="container">

    {% for department in department_list %}
      <hr>
      <ul>

        <li> <h4>Department: <a href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}"> {{department.name}}</h2></a> </li>
        <ul>
          <li> <h6> HoD : {{department.chairman}} </h3> </li>
          <li><h6>Faculty : {{department.faculty.name}}</h2> </li>
          <li><h6>Total teachers in {{department.name}} : {{department.teachers.count}} </h2></li>
          <li><h6>Total students in {{department.name}} : {{department.students.count}} </h2></li>
          <li> <h6>Established at: {{department.established_date}}</h2> </li>
        </ul>

      </ul><hr>
    {% endfor %}
  </div>
{% endif %}

</section>


{% endblock %}

departments/templates/departments/department_students.html
{% extends "faculties/faculty_base.html" %}

{% block content %}

  <div class="container jumbotron">

    <h3><a href="{% url 'faculties:faculty_detail' faculty_slug=department.faculty.faculty_slug %}"><span style="color:#1bac91;"> {{department.faculty.name}}</a> </span> </h1>
      <br>
    <h2>All Students of <a style="font-size:24px;" href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}">{{department.name}}</a> </h2>

    <br><br>
    <h6><span style="font-weight:bold">Total students:</span> {{department.students.count }}</h2>

    <br>
    {# <h5> {{department.detail_html|safe}}</h4><br><br> #}

  </div>


  <div class="container">
    <section id="steps" class="steps section-bg" style="background-color:#fafcff">


      <hr>
      {% if department.students.count == 0 %}
        <h5>No students admitted in this department.</h5>

      {% else %}

      <table id="details_table" align="center">
        <thead style="color:blue">
          <th>Profile Pic</th>
          <th> <p>Student Username </p> </th>
          <th> <p>Student ID</p> </th>
          <th> <p>Email</p> </th>
          <th><p>Department</p> </th>
          <th> <p>Session </p> </th>
        </thead>
        <tr >
          <td class="extra-row"><br> </td>
          <td class="extra-row"><br> </td>
        </tr>

        {% for student in department.students.all %}
        <tr>
          {% if student.profile_pic %}
           <td><img src="{{ student.profile_pic.url }}"  height=120 width=120 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=120 width=120 alt=""></td>
          {% endif %}

          <td><p> <a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %} " style="color:#1bac91; font-size:19px"> {{student.user.username}}</a> </h4></td>
          <td> {{ student.student_ID }} </td>

          {% if student.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{student.user.email}}</p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</p> </td>
          {% endif %}

          <td> {{ student.department.acronyms }} </td>
          <td><p> <span style="color:#2f5b9c;">{{student.session}}</p> </td>
        </tr>

        <tr >
          <td class="extra-row"><br> </td>
        </tr>
        <tr >
        </tr>
        {% endfor %}
      </table>
      {% endif %}

      <hr>

    </section>
  </div>

<br><br><br>

{% endblock %}

departments/templates/departments/department_teachers.html
{% extends "faculties/faculty_base.html" %}

{% block content %}

  <div class="container jumbotron">

    <h3><a href="{% url 'faculties:faculty_detail' faculty_slug=department.faculty.faculty_slug %}"><span style="color:#1bac91;"> {{department.faculty.name}}</a> </span> </h1>
      <br>
    <h2>All Teachers of <a style="font-size:24px;" href="{% url 'departments:department_detail' faculty_slug=department.faculty.faculty_slug department_slug=department.department_slug %}">{{department.name}}</a> </h2>

    <br><br>
    <h6><span style="font-weight:bold">Total teachers:</span> {{department.teachers.count }}</h2>

    <br>
    {# <h5> {{department.detail_html|safe}}</h4><br><br> #}

  </div>


  <div >
    <section id="steps" class="container steps section-bg" style="background-color:#fafcff">

      {% if department.teachers.count == 0 %}
        <h5>No teachers recruited in this department.</h5>

      {% else %}
      <table id="details_table" align="center">
        <thead style="color:blue">
          <th>Profile Pic</th>
          <th> <p>Username </p> </th>
          <th> <p>Academic Rank</p> </th>
          <th> <p>Teacher ID</p> </th>
          <th> <p>Email</p> </th>
          <th><p>Department</p> </th>

        </thead>
        <tr >
          <td class="extra-row"><br> </td>
          <td class="extra-row"><br> </td>
        </tr>

        {% for teacher in department.teachers.all %}
        <tr>
          {% if teacher.profile_pic %}
           <td><img src="{{ teacher.profile_pic.url }}"  height=150 width=150 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=150 width=150 alt=""></td>
          {% endif %}

          <td><p> <a href="{% url 'teachers:teacher_detail' department_slug=teacher.department.department_slug teacher_slug=teacher.teacher_slug %} " style="color:#1bac91; font-size:19px"> {{teacher.user.username}}</a> </h4></td>
          <td> {{teacher.academic_rank}} </td>
          <td> {{ teacher.Teacher_ID }} </td>

          {% if teacher.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{teacher.user.email}}</p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</p> </td>
          {% endif %}

          <td> {{ teacher.department.acronyms }} </td>
          <td><p> <span style="color:#2f5b9c;">{{teacher.session}}</p> </td>
        </tr>
        <tr >
          <td class="extra-row"><br> </td>
        </tr>
        <tr >
        </tr>
        {% endfor %}
      </table>

      {% endif %}

    </section>
  </div>

<br><br><br>

{% endblock %}

departments/templates/departments/department_update.html
{% extends 'departments/department_base.html' %}
{% load bootstrap4 %}

{% block content %}

    <section id="steps" class="steps section-bg">

      <div class="container">
        <h3>Update <span style="color:#1bac91; font-size:22px">{{ department.name }}</span> </h1>
          <br>
        <form method="POST" class="post-form">
        {% csrf_token %}

        {% bootstrap_form form %}


        <input type="submit" class="btn btn-primary"></input>

        </form>
      </div>
    </section>


{% endblock %}